version: '3'

services:
  myproject:
    build:
      context: .
      # dockerfile: Dockerfile
    image: myproject
    container_name: myproject
    # restart: unless-stopped
    # ports:
    #   - "80:8080"
    volumes:
      - ./logs:/nodejs_auto_close_shutdown_archive/logs
    # networks:
    #   - app-network
    command: npm start

    # docker compose up -d