version: '3'

services:
  myproject:
    build:
      context: .
      # dockerfile: Dockerfile
    image: myproject
    container_name: myproject
    # restart: unless-stopped
    # ports:
    #   - "80:8080"
    volumes:
      - ~/projects/pppur/logs/AutoCloseService:/app/logs
    # networks:
    #   - app-network
    command: npm start

    # docker compose up -d - запуск
    # docker compose up -build -d - запуск с пересборкой